// Generated by CoffeeScript 1.6.3
(function() {
  var assert, fileTemp, fileTest, fs, i18nStringsFiles, should;

  fs = require('fs');

  assert = require('assert');

  should = require('should');

  i18nStringsFiles = require('../index');

  fileTest = __dirname + '/test.strings';

  fileTemp = __dirname + '/temp.strings';

  describe('Reading file into object', function() {
    return it('should populate object properties with values', function() {
      var data;
      data = i18nStringsFiles.readFileSync(fileTest, 'UTF-8');
      return data.login_button.should.equal('Log In');
    });
  });

  describe('Read, compile, parse', function() {
    return it('should populate object properties with values before and after', function() {
      var data, str;
      data = i18nStringsFiles.readFileSync(fileTest, 'UTF-8');
      data.login_button.should.equal('Log In');
      str = i18nStringsFiles.compile(data);
      data = i18nStringsFiles.parse(str);
      return data.login_button.should.equal('Log In');
    });
  });

  describe('Read, write, read', function() {
    return it('should populate object properties with values before and after', function() {
      var data;
      data = i18nStringsFiles.readFileSync(fileTest, 'UTF-8');
      data.login_button.should.equal('Log In');
      i18nStringsFiles.writeFileSync(fileTemp, data, 'UTF-8');
      data = i18nStringsFiles.readFileSync(fileTemp, 'UTF-8');
      fs.unlinkSync(fileTemp);
      return data.login_button.should.equal('Log In');
    });
  });

}).call(this);
